### ISSUE TITLE
JPG file quality

### ISSUE THREAD

**Issue by jwtc-lin** [i-TechSoftware/RtspClientSharpCore#3]
Why is the image quality of JPG files worse than the actual camera?
How to adjust?

**Comment by i-TechSoftware** [comment]
I have no answer to this question. This may be for various reasons, but none, most likely, will be relevant to this project. I use this code in my enterprise solution and have not encountered such problems.

**Comment by askrinnik** [comment]
Generally speaking, JPG format means that picture quality may be worse due to compression
My suggestion is do not download or save in JPG
